version: "3"

volumes:
  data:
  db:

networks:
  proxy:
    external:
      name: proxy
  default:

services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}

  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:apache
    restart: always
    volumes:
      - data:/var/www/html
      - ${NAS_STORAGE}:/mnt
    environment:
      - POSTGRES_HOST=db:5432
      - REDIS_HOST=redis
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
    depends_on:
      - db
      - redis
    networks:
      - default
      - proxy

  cron:
    image: nextcloud:apache
    restart: always
    volumes:
      - data:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
