---
- hosts: localhost
  become: true
  tasks:
  - name: Upgrade all packages
    ansible.builtin.dnf:
      name: "*"
      state: latest
  - name: install podman
    ansible.builtin.package: name=podman state=latest
  - name: Creates container mount dir
    file:
      path: /storage/containers
      state: directory
  - name: Creates NAS mount dir
    file:
      path: /storage/nas
      state: directory
  - name: Mount container NFS mount
    ansible.posix.mount:
      src: 10.0.1.10:/ssd/containers
      path: /storage/containers
      opts: rw,sync,hard
      state: mounted
      fstype: nfs
  - name: Mount NAS NFS mount
    ansible.posix.mount:
      src: 10.0.1.10:/hdd/nas
      path: /storage/nas
      opts: rw,sync,hard
      state: mounted
      fstype: nfs
